# Google Cloud Build configuration for Cloud Run deployment
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', 
      '-t', 'gcr.io/$PROJECT_ID/gcp-token-server:$COMMIT_SHA', 
      '.'
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 
      'gcr.io/$PROJECT_ID/gcp-token-server:$COMMIT_SHA'
    ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'gcp-token-server',
      '--image', 'gcr.io/$PROJECT_ID/gcp-token-server:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8000',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '100',
      '--set-env-vars', 'PORT=8000'
    ]

images:
  - gcr.io/$PROJECT_ID/gcp-token-server:$COMMIT_SHA